### ISSUE TITLE
InvalidArgumentException when installing via composer

### ISSUE THREAD

**Issue by Miojo** [adinan-cenci/cache#1]
Using php 7.0:
command:
composer require adinan-cenci/cache 

gives:
[InvalidArgumentException]
  Could not find a matching version of package adinan-cenci/cache. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability
   (stable).

**Comment by adinan-cenci** [comment]
Sorry for taking so long to answear.
You are right, I didn't submited my code to packagist.

You probably already found the solution for your problem, but the library is now on packagist and ready for use. Hope it helps.
